const strings = {
    internal_server_error: "An internal server error occurred.",
    username_taken: "Username taken.",
    email_used: "Email already in use.",
    invalid_username: "Invalid username.",
    invalid_email: "Invalid email.",
    invalid_password: "Invalid password.",
    register_success: "User registered successfully.",
    not_found: "Resource not found.",
    invalid_login: "Invalid username or password.",
    verify_email: "Please verify your email.",
    login_success: "Login successful.",
    bad_request: "Bad request.",
    invalid_verification_key: "Invalid verification key.",
    invalid_verification_code: "Invalid verification code.",
    verified_successfully: "Email verified successfully.",
    email_not_allowed: "The email address provided cannot be used.",
    unauthorized: "Unauthorized.",
    forbidden: "Forbidden.",
    server_create_success: "Server created successfully.",
    channel_success: "Channel created successfully.",
    file_success: "File uploaded successfully.",
    two_factor_already_enabled: "2FA has already been enabled on this account.",
    two_factor_already_disabled: "2FA is not enabled on this account.",
    verify_enable_2fa: "Please save 2FA and verify.",
    missing_2fa_code: "Missing 2FA code.",
    invalid_2fa: "Invalid 2FA code.",
    two_factor_enabled: "2FA enabled successfully.",
    two_factor_disabled: "2FA disabled successfully.",
    generate_2fa_first: "You must request to generate a secret first.",
    email_resent: "Email resent.",
    recovery_sent: "Recovery code sent.",
    password_reset_success: "Password reset successfully.",
    verification_accepted: "verification code accepted.",
    expired: "Expired.",
    user_found: "User found successfully.",
};

export default strings;
